[package]
name = "distributed_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
ed25519-dalek = "1.0"
rand = "0.8"
bellman = "0.9"
pairing = "0.17"
ff = "0.10"
clap = { version = "3.0", features = ["derive"] }