[package]
name = "privacy_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
hex = "0.4"
tokio = { version = "1.18", features = ["full"] }
ed25519-dalek = "1.0"
rand = "0.8"
clap = { version = "3.2", features = ["derive"] }
bellman = "0.9.0"
pairing = "0.17.0"
ff = "0.10.1"
chrono = "0.4"
bincode = "1.3"